# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e67c83c763812cc9120be5b10db38c3ce14131085cbd387a7eac78d52271e07dc961ef44ed7248333cf084c19681bee23aa1feb92990b26eae0fa673e0b7c1e2

test:
  secret_key_base: e5dafcf433e952b796ef3ef6448334aeb8c60796d40faf0ea25f8be40b178aad1264ce673e2c09ec2f72ab50a3b690a346d819ca2c77553ab652f5973401ec2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
